import React from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './Legal.module.css';

export const TermsScreen: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className={styles.container}>
      <button onClick={() => navigate(-1)} className={styles.backButton}>
        ← Back
      </button>
      
      <h1 className={styles.title}>Terms of Service</h1>
      
      <div className={styles.section}>
        <h2>1. Medical Disclaimer</h2>
        <p>
          <strong>Grow Baby Grow is NOT a medical device.</strong> The information, including but not limited to, text, graphics, images, and other material contained in this app are for informational purposes only.
        </p>
        <p>
          No material in this app is intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your pediatrician or other qualified health care provider with any questions you may have regarding a medical condition or treatment and before undertaking a new health care regimen.
        </p>
      </div>

      <div className={styles.section}>
        <h2>2. Data Accuracy</h2>
        <p>
          While we strive to use the latest clinical guidelines (WHO, IAP, AIIMS), the interpretations and growth curves generated by the app are dependent on the data you provide. We do not guarantee the clinical accuracy of the charts for diagnostic purposes.
        </p>
      </div>

      <div className={styles.section}>
        <h2>3. Data Responsibility</h2>
        <p>
          As an offline-first app, you are solely responsible for backing up your data. If you lose your device or clear your browser data without a backup, your records cannot be recovered by us.
        </p>
      </div>

      <div className={styles.section}>
        <h2>4. Permitted Use</h2>
        <p>
          This application is provided free of charge for personal, non-commercial use. You may not reverse-engineer or attempt to extract the underlying clinical database for external commercial redistribution.
        </p>
      </div>

      <div className={styles.footer}>
        Last updated: April 2026
      </div>
    </div>
  );
};
